### ISSUE TITLE
docker-machine-hypriot does not work as driver only standalone

### ISSUE THREAD

**Issue by jottr** [hypriot/docker-machine-hypriot#3]
```
$ docker-machine --version
docker-machine version 0.5.1 (7e8e38e)

$ docker-machine-driver-hypriot
docker-machine-driver-hypriot version 0.4.1 (f7caa56)

```

When trying to use the hypriot driver, the following happens:

```
$ docker-machine create --driver hypriot --hypriot-ip-address=$HYPRIOT_IP_ADDRESS foo
Error loading driver "hypriot": dial tcp: unexpected '[' in address Usage: docker-machine-driver-hypriot [OPTIONS] COMMAND [arg...]
```

but using the drivers binary itself works without problems:

```
$ docker-machine-driver-hypriot  create --driver hypriot --hypriot-ip-address=$HYPRIOT_IP_ADDRESS foo
```

**Comment by StefanScherer** [comment]
@jottr Oh you are trying to mix versions. The old binaries `docker-machine-*` from our download page are complete docker-machine binaries with the hypriot driver and provisioner compiled into it. You can't use this as a plugin driver for docker-machine 0.5.x.

And the plugin driver for 0.5.x only has the plugin, but not the provisioner inside. We have to sort out how we proceed with this plugin or whether we try to send a PR to add a hypriot/raspbian provisioner into the [docker/machine](https://github.com/docker/machine) repo.

**Comment by jottr** [comment]
Ok, just to clarify: We should use `docker-machine-hypriot-driver` as a standalone for now?  
What about the README for this repo? It states we should make `docker-machine-hypriot-driver` binary available in our path, and then goes on to explain how to use the plugin driver.

**Comment by StefanScherer** [comment]
@jottr I have updated the README.md with commit [27aaa54c53a2bcce2fd099911b3f08ba23f87b12](https://github.com/hypriot/docker-machine-hypriot/commit/27aaa54c53a2bcce2fd099911b3f08ba23f87b12) to make it more clear that the old binary is no "driver" plugin for docker-machine 0.5.x. The README itself points to a non-existing release 0.0.1 of the plugin.
Please have a look at the discussion #1 that we more need a provisioner rather than a driver plugin. :-)
